name: Daily Article
on:
  schedule:
    - cron: '0 8 * * 1,3,5'  # Lundi, mercredi, vendredi 8h UTC
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AFFILIATE_ID: ${{ secrets.AFFILIATE_ID }}
      UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install --upgrade pip
      - run: pip install requests
      - run: python gen_article.py
        continue-on-error: true
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Nouvel article" || echo "No changes to commit"
          git push
